"""Export decision run to Markdown and JSON."""

from __future__ import annotations

import json

from app.core.schemas import DecisionRun, MetricId


def export_memo_markdown(decision_run: DecisionRun) -> str:
    """Export the memo + metadata as a Markdown document."""
    lines = [
        f"# IC Memo — Decision Run {decision_run.run_id[:8]}",
        "",
        f"**Run ID:** `{decision_run.run_id}`",
        f"**Timestamp:** {decision_run.timestamp}",
        f"**Input Hash:** `{decision_run.input_hash[:16]}...`",
        f"**Metric Version:** {decision_run.metric_version}",
        f"**Benchmark:** {decision_run.benchmark.symbol if decision_run.benchmark else 'None'}",
        "",
        "---",
        "",
        "## Universe Summary",
        "",
        f"- **Funds evaluated:** {len(decision_run.universe.funds)}",
        f"- **Candidates included:** {sum(1 for rc in decision_run.run_candidates if rc.included)}",
        f"- **Candidates excluded:** {sum(1 for rc in decision_run.run_candidates if not rc.included)}",
        f"- **Validation warnings:** {len(decision_run.universe.warnings)}",
        "",
        "## Mandate Configuration",
        "",
    ]

    mandate = decision_run.mandate
    lines.append(f"- Name: {mandate.name}")
    if mandate.min_liquidity_days is not None:
        lines.append(f"- Min liquidity: {mandate.min_liquidity_days} days")
    if mandate.max_drawdown_tolerance is not None:
        lines.append(f"- Max drawdown tolerance: {mandate.max_drawdown_tolerance:.1%}")
    if mandate.target_volatility is not None:
        lines.append(f"- Target volatility: {mandate.target_volatility:.1%}")
    if mandate.strategy_include:
        lines.append(f"- Strategy include: {', '.join(mandate.strategy_include)}")
    if mandate.strategy_exclude:
        lines.append(f"- Strategy exclude: {', '.join(mandate.strategy_exclude)}")
    weights_str = ", ".join(
        f"{mid.value}={w}" for mid, w in mandate.weights.items()
    )
    lines.append(f"- Weights: {weights_str}")

    # Excluded candidates
    excluded = [rc for rc in decision_run.run_candidates if not rc.included]
    if excluded:
        lines.extend(["", "## Excluded Candidates", ""])
        for rc in excluded:
            lines.append(f"- {rc.fund_name}: {rc.exclusion_reason}")

    lines.extend(["", "## Ranked Shortlist", ""])
    lines.append(
        "| Rank | Fund | Return | Vol | Sharpe | Max DD | Score | Constraints |"
    )
    lines.append("|------|------|--------|-----|--------|--------|-------|-------------|")

    for sf in decision_run.ranked_shortlist:
        m = sf.metric_values
        ret = m.get(MetricId.ANNUALIZED_RETURN, 0)
        vol = m.get(MetricId.ANNUALIZED_VOLATILITY, 0)
        sharpe = m.get(MetricId.SHARPE_RATIO, 0)
        dd = m.get(MetricId.MAX_DRAWDOWN, 0)
        status = "Pass" if sf.all_constraints_passed else "FAIL"
        lines.append(
            f"| {sf.rank} | {sf.fund_name} | {ret:.2%} | {vol:.2%} | "
            f"{sharpe:.2f} | {dd:.2%} | {sf.composite_score:.3f} | {status} |"
        )

    if decision_run.memo:
        lines.extend(["", "---", "", "## Memo", "", decision_run.memo.memo_text])

        if decision_run.memo.claims:
            lines.extend(["", "## Claims", ""])
            for claim in decision_run.memo.claims:
                metrics_str = ", ".join(m.value for m in claim.referenced_metric_ids)
                funds_str = ", ".join(claim.referenced_fund_names)
                lines.append(f"- **[{claim.claim_id}]** {claim.claim_text}")
                lines.append(f"  - Metrics: {metrics_str}")
                lines.append(f"  - Funds: {funds_str}")

    lines.extend(["", "---", "", f"*Generated by Equi Decision Engine*"])
    return "\n".join(lines)


def export_decision_run_json(decision_run: DecisionRun) -> str:
    """Export the full DecisionRun as formatted JSON for archival."""
    return decision_run.model_dump_json(indent=2)
